import * as React from "react";
import Head from "next/head";
import Container from "/project/cafe-table/src/containers/home";
import Top from "/project/cafe-table/src/components/top-bar";
import Layout from "/project/cafe-table/src/components/layout";
import Bottom from "/project/cafe-table/src/components/bottom-bar";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container />
    </>
  );
}

HomePage.getLayout = function getLayout(page) {
  return (
    <React.Fragment>
      <Top />
      <Layout>{page}</Layout>
      <Bottom />
    </React.Fragment>
  );
};
