import * as React from "react";
import Head from "next/head";
import Container from "/project/cafe-table/src/containers/search";
import App from "/project/cafe-table/src/components/app-bar";
import Bar from "/project/cafe-table/src/components/search";
import Layout from "/project/cafe-table/src/components/layout";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container />
    </>
  );
}

HomePage.getLayout = function getLayout(page) {
  return (
    <React.Fragment>
      <App />
      <Layout>{page}</Layout>
    </React.Fragment>
  );
};
